import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Sideplayer from "@/components/Sideplayer";
import DesktopSearchbar from "@/components/DesktopSearchbar";
import MusicPlayer from "@/components/MusicPlayer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import MobileNav from "@/components/MobileNav";
import MobileHeader from "@/components/MobileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-background flex flex-col md:flex-row">
          <div className="md:hidden w-full">
            <div className="h-[30px] w-full" />
            <MobileHeader />
          </div>
          <div className="hidden md:flex">
            <Sidebar />
          </div>
          <div className="md:hidden">
            <MobileNav />
          </div>
          <main className="md:ml-[144px] xl:w-[calc(100%-508px)] md:w-[calc(100%-144px)] pb-[120px]">
            <nav className="py-[20px]">
              <DesktopSearchbar />
            </nav>
            {children}
          </main>
          <Sideplayer />
          <MusicPlayer />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
